### PR TITLE
Adds in the ability to set rcvbuf and sndbuf parameters.

### PR DESCRIPTION
**Pull request by typhonius**
I use puppet-openvpn.
I read [this article](http://lowendtalk.com/discussion/comment/843561).
I figured it'd be useful to include.
Panda :panda_face:

### CODE REVIEW

**Comment by luxflux** [comment]
Thanks for your code! :beers: That's really a good thing to add these parameters.

According to the article, the parameters are needed on server and client side. Could you add the client side as well? Thanks a lot!

**Comment by luxflux** [comment]
Ah, could you merge master? I "fixed" the travis build.

**Comment by typhonius** [comment]
- Rebased on upstream/master
- Client config and tests added
- Commits flattened into single commit

Good call on adding client config. I omitted it personally as I cannot change client config on our set up. Instead I push the config:

````
    push         => [
      "sndbuf 393216",
      "rcvbuf 393216",
    ],
    sndbuf       => 393216,
    rcvbuf       => 393216,
````

**Comment by luxflux** [comment]
Thanks a lot!

**Pull request merged**
